export const HOME = '/';
export const ABOUT = '/about';
export const APPMAP = '/app'
// export const WELCOME = '/Welcome';
export const GITHUB = 'https://github.com/KayoRonald/euajudo-app';
// export const SIGN_IN = '/login';
// export const FORGOT = '/forgot-password';
export const TEAM = '/team';
export const DISCORD = 'https://discord.gg/cuMzJwC99G';